
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bit64\Bundle\ApiUtilsBundle\EventListener\:
        resource: '../../../src/EventListener'

    Bit64\Bundle\ApiUtilsBundle\Services\:
        resource: '../../../src/Services'

    Bit64\Bundle\ApiUtilsBundle\Security\AuthenticationProvider:
    Bit64\Bundle\ApiUtilsBundle\Security\FirewallListener:
